name: Build
on:
  push:
    branches:
      - '**'
jobs:
  build:
    runs-on: macos-14-xlarge
    strategy:
      fail-fast: false
      matrix:
        xcodeversion: [ 15.1, 15.3 ]
    steps:
      - uses: actions/checkout@v4.1.6
      - uses: maxim-lobanov/setup-xcode@v1.6.0
        with:
          xcode-version: ${{ matrix.xcodeversion }}
      - uses: ./.github/actions/runGradleTask
        with:
          task: assemble
  barrier-build:
    runs-on: ubuntu-22.04
    needs: [ build ]
    steps:
      - run: exit 0
